sudo: required
services:
  - docker

before_install:
  - docker build -t kevinmaillet/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kevinmaillet/react-test npm test

after_success:
  - docker build -t kevinmaillet/multi-client ./client
  - docker build -t kevinmaillet/multi-nginx ./nginx
  - docker build -t kevinmaillet/multi-server ./server
  - docker build -t kevinmaillet/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push kevinmaillet/multi-client
  - docker push kevinmaillet/multi-nginx
  - docker push kevinmaillet/multi-server
  - docker push kevinmaillet/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-864688217542
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
